extra-deps:
- distributed-process-0.7.3
- distributed-process-simplelocalnet-0.2.4
- network-transport-0.5.2
- network-transport-tcp-0.6.0
resolver: lts-9.12
flags: {}
extra-package-dbs: []
packages:
- .
